# Generated by Django 3.0.4 on 2020-05-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='ParkingSpotID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(default=0),
        ),
    ]
