# Generated by Django 3.0.4 on 2020-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200501_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='FirstName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(max_length=20),
        ),
    ]
