# Generated by Django 3.0.4 on 2020-05-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200501_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
    ]
